### ISSUE TITLE
TODO/FIXME Count 9

### ISSUE THREAD

**Issue by JSAssassin** [digitalbazaar/bedrock-kms#25]
- [ ] FIXME: should updating controller be allowed?
     Commit: (090589d) Add keystore API tests.
     [test/mocha/13-keystores-update-api.js:256](https://github.com/digitalbazaar/bedrock-kms/blob/master/test/mocha/13-keystores-update-api.js#L256)
     Matthew Collier commented a month ago

  - [ ] FIXME: should updating controller be allowed?
     Commit: (090589d) Add keystore API tests.
     [test/mocha/13-keystores-update-api.js:243](https://github.com/digitalbazaar/bedrock-kms/blob/master/test/mocha/13-keystores-update-api.js#L243)
     Matthew Collier commented a month ago

  - [ ] FIXME: should updating controller be allowed?
     Commit: (090589d) Add keystore API tests.
     [test/mocha/13-keystores-update-api.js:227](https://github.com/digitalbazaar/bedrock-kms/blob/master/test/mocha/13-keystores-update-api.js#L227)
     Matthew Collier commented a month ago

  - [x] TODO: support RsaSignature2018 and other suites?
       Commit: (38c4c8b) Use keystores.
       [lib/index.js:86](https://github.com/digitalbazaar/bedrock-kms/blob/master/lib/index.js#L86)
       Dave Longley commented a year ago

  - [ ] FIXME
       Commit: (7565d7b) Add context, fix didIo resolution.
       [lib/index.js:55](https://github.com/digitalbazaar/bedrock-kms/blob/master/lib/index.js#L55)
       Dmitri Zagidulin commented a month ago

  - [x] TODO: remove deprecated `allowedHosts`
       Commit: (14223e7) Require a single configured `allowedHost`.
       [lib/index.js:32](https://github.com/digitalbazaar/bedrock-kms/blob/master/lib/index.js#L32)
       Dave Longley commented 10 months ago

  - [x] TODO: Move v1 'test' mode param to config.
       Commit: (32908bb) Support Veres One type DIDs in the documentLoader.
       [lib/index.js:22](https://github.com/digitalbazaar/bedrock-kms/blob/master/lib/index.js#L22)
       Dmitri Zagidulin commented a month ago

  - [ ] FIXME: should updating controller be allowed?
     Commit: (090589d) Add keystore API tests.
     [test/mocha/13-keystores-update-api.js:274](https://github.com/digitalbazaar/bedrock-kms/blob/master/test/mocha/13-keystores-update-api.js#L274)
     Matthew Collier commented a month ago

  - [ ] FIXME: should updating controller be allowed?
     Commit: (090589d) Add keystore API tests.
     [test/mocha/13-keystores-update-api.js:288](https://github.com/digitalbazaar/bedrock-kms/blob/master/test/mocha/13-keystores-update-api.js#L288)
     Matthew Collier commented a month ago

**Comment by dlongley** [comment]
This has been addressed, closing.
